version: '3.9'
services:
  postgres:
    stdin_open: true
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ng
      POSTGRES_PASSWORD: ng
      POSTGRES_DB: ng
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  ng-server:
    build: .
    image: "ng-server"
    container_name: ng-server
    ports:
      - 3333:3333
    depends_on:
      - postgres
    restart: always
    
  ng-web:
    build: .
    image: "ng-web"
    container_name: ng_web
    ports:
      - 3000:3000
    depends_on:
      - ng-server

volumes:
  postgres-data: